import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import WebSocket from 'ws';
import { ApiServer } from '../src/api.js';
import { encodeV2Frame } from '../src/mavlink.js';

test('HTTP and WebSocket enforce login, scoped telemetry, grants and read-only real connections',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'management-http-'));process.env.DRONE_DATA_DIR=dir;
  const api=new ApiServer({port:0,dataDir:dir,logger:{info(){},error(){}}});await api.start();const port=api.http.address().port,base=`http://127.0.0.1:${port}`;
  const sockets=[];t.after(async()=>{for(const ws of sockets)ws.terminate();api.stop();await rm(dir,{force:true,recursive:true});});
  const request=async(path,method='GET',body,cookie)=>{const r=await fetch(base+'/api'+path,{method,headers:{'content-type':'application/json',...(cookie?{cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
  assert.equal((await request('/drones')).status,401);
  assert.equal((await fetch(base+'/api/drones',{headers:{'x-api-token':'dsh-demo-token'}})).status,401);
  const password=/密码：(.+)/.exec(await readFile(join(dir,'bootstrap-admin.txt'),'utf8'))[1].trim();
  const login=await request('/v2/login','POST',{username:'admin',password});assert.equal(login.status,200);const cookie=login.cookie;
  const org=(await request('/v2/organizations','POST',{name:'测试站'},cookie)).body;
  const user=(await request('/v2/users','POST',{name:'观察员',username:'viewer-test',password:'viewer-test-password',orgId:org.id,roleId:'viewer'},cookie)).body;
  assert.equal(user.passwordHash,undefined);
  const limited=(await request('/v2/login','POST',{username:'viewer-test',password:'viewer-test-password'})).cookie;
  assert.equal((await request('/v2/users/admin','GET',null,limited)).status,403);
  assert.equal((await request('/v2/assets','POST',{name:'未经授权'},limited)).status,403);
  const heartbeat=sysid=>encodeV2Frame({sysid,compid:1,msgid:0,payload:Buffer.from('00000000020c510303','hex')});
  await api.gateway.receive(heartbeat(23),{transport:'udp',host:'127.0.0.1',port:12345});
  await api.gateway.receive(heartbeat(24),{transport:'udp',host:'127.0.0.1',port:12345});
  await request('/v2/assets','POST',{name:'本单位飞控',kind:'无人机',serial:'unit-23',droneId:'real-23',orgId:org.id},cookie);
  assert.deepEqual((await request('/drones','GET',null,limited)).body.drones.map(d=>d.droneId),['real-23']);
  assert.equal((await request('/telemetry/real-24','GET',null,limited)).status,404);
  assert.equal((await request('/drones/real-23/arm','POST',{},cookie)).status,409);
  const foreign=await fetch(base+'/api/v2/assets',{method:'POST',headers:{cookie,origin:'http://other.invalid','content-type':'application/json'},body:'{}'});assert.equal(foreign.status,403);
  const ws=new WebSocket(`ws://127.0.0.1:${port}/ws`,{headers:{cookie:limited}});sockets.push(ws);
  const first=JSON.parse((await once(ws,'message'))[0]);assert.deepEqual(first.data.drones.map(d=>d.droneId),['real-23']);
  const reply=once(ws,'message');ws.send(JSON.stringify({type:'command',droneId:'real-23',command:{command:400}}));assert.equal(JSON.parse((await reply)[0]).data.ok,false);
  await request('/v2/logout','POST',{},limited);const close=once(ws,'close');api._broadcast({type:'state',data:{droneId:'real-23'}});assert.equal((await close)[0],1008);
  const media=(await request('/v2/media','POST',{name:'接口归档',kind:'日志',filename:'log.txt',mime:'text/plain',contentBase64:Buffer.from('telemetry record').toString('base64')},cookie)).body;
  const download=await fetch(base+`/api/v2/media/${media.id}/content`,{headers:{cookie}});assert.equal(await download.text(),'telemetry record');
  assert.equal((await fetch(base+`/api/v2/media/${media.id}/content`,{headers:{cookie:limited}})).status,401);
  assert.equal((await request('/v2/fences/import','POST',{features:[{type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[0,0]]]}]},cookie)).status,201);
  assert.equal((await request('/v2/schedules/missing/execute','POST',{},cookie)).status,404);
});
